_target_: pytorch_lightning.Trainer

accelerator: gpu
devices:
- 0

min_epochs: 1
max_epochs: 200

accumulate_grad_batches: 1
#gradient_clip_val: 1

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

