_target_: pytorch_lightning.Trainer

gpus:
- 1

min_epochs: 1
max_epochs: 200

# accumulate_grad_batches: 5
# detect_anomaly: True
# gradient_clip_val: 1
# gradient_clip_algorithm: value

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
