_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cont_cnn_rf.CCNN
  in_channels: 32
  kernel_size: 5
  nb_filters: 16
  nb_layers: 9
  num_types: 8
  hidden_1: 8
  hidden_2: 4
  hidden_3: 8
metrics:
  _target_: src.metrics.cont_cnn.cont_cnn_rf.CCNNMetricsRF
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
  sim_size: 40
optimizer:
  name: adam
  params:
    lr: 1e-3
    weight_decay: 1e-5
