_target_: src.models.extra_head_model.ExtrHeadEventModule

net:
  _target_: src.models.components.cont_cnn.CCNN
  in_channels: 32
  kernel_size: 5
  nb_filters: 16
  nb_layers: 9
  num_types: 8
  hidden_1: 8
  hidden_2: 4
  hidden_3: 8
head:
  _target_: src.models.components.cont_cnn.PredictionHead
  in_channels: 16
  num_types: 8
metrics:
  _target_: src.metrics.cont_cnn.CCNNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
  type_loss_coeff: 1
  time_loss_coeff: 10
  sim_size: 50
  gamma_reg: False
  alpha: 1.001
  beta: 0.001
optimizers:
  0:
      name: adam
      params:
        lr: 0.01
        weight_decay: 1e-8
      milestones:
        - 20
        - 30
        - 40
      gamma: 0.5
  1:
      name: adam
      params:
        lr: 1e-3
        weight_decay: 1e-8
enc_output_only_head: True
