_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cont_cnn.CCNN
  in_channels: 32
  kernel_size: 9
  nb_filters: 16
  nb_layers: 3
  num_types: ${num_types}
  kernel:
    _target_: src.models.components.cont_cnn.Kernel
    hidden1: 8
    hidden2: 4
    hidden3: 8
    in_channels: ${model.net.nb_filters}
    out_channels: ${model.net.nb_filters}
  head:
    _target_: src.models.components.cont_cnn.PredictionHead
    in_channels: ${model.net.nb_filters}
    num_types: ${num_types}
metrics:
  _target_: src.metrics.cont_cnn.CCNNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
  type_loss_coeff: 1
  time_loss_coeff: 1
  reductions:
    log_likelihood: sum
    type: sum
    time: sum
  sim_size: 36
optimizer:
  name: adam
  params:
    lr: 0.01
    weight_decay: 1e-8
scheduler:
  step: 50
  milestones: null
  #   - 40
  #   - 75
  gamma: 0.5
head_start: 1
