_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cont_cnn.CCNN
  in_channels: 32
  kernel_size: 5
  nb_filters: 16
  nb_layers: 9
  num_types: ${num_types}
  kernel:
    _target_: src.models.components.cont_cnn.Kernel
    hidden1: 8
    hidden2: 4
    hidden3: 8
    in_channels: ${model.net.nb_filters}
    out_channels: ${model.net.nb_filters}
  head:
    _target_: src.models.components.cont_cnn.PredictionHead
    in_channels: ${model.net.nb_filters}
    num_types: ${num_types}
metrics:
  _target_: src.metrics.cont_cnn.CCNNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
  sim_size: 40
  gamma_reg: False
  alpha: 1.0
  beta: 0
optimizers:
  0:
      name: adam
      params:
        lr: 0.0
        weight_decay: 1e-5
  1:
      name: adam
      params:
        lr: 1e-5
        weight_decay: 1e-5
enc_output_only_head: True
