_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cotic.cotic.COTIC
  in_channels: 192
  kernel_size: 3
  nb_filters: 512
  nb_layers: 8
  num_types: ${num_types}
  dropout: 0.2
  dilation_factor: 1.29
joined_head:
  _target_: src.models.components.cotic.head.joined_head.ProbabilisticJoinedHead # JoinedHead
  intensity_head:
    _target_: src.models.components.cotic.head.intensity_head.IntensityHeadLinear
    kernel_size: 1
    nb_filters: ${model.net.nb_filters}
    num_types: ${num_types}
  downstream_head:
    _target_: src.models.components.cotic.head.downstream_head.DownstreamHeadSklearnLinear # ProbabilisticDownstreamHead # DownstreamHeadSklearnLinear #DownstreamHeadLinear
    compute_every_n_epochs: null
    nb_filters: ${model.net.nb_filters} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
    num_types: ${num_types} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
    fit_every_n_epochs: 1
##    type_loss_coeff: 1 # DownstreamHeadLinear
##    time_loss_coeff: 10 # DownstreamHeadLinear
##    reductions: 2 # DownstreamHeadLinear
##      type: mean # DownstreamHeadLinear
##      time: mean # DownstreamHeadLinear
  uniform_sample_size: 50
optimizer:
  _target_: adan_pytorch.Adan
  _partial_: true
  lr: 0.001
  weight_decay: 0.003
init_lr: ${model.optimizer.lr}
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 5
  factor: 0.5
scheduler_monitoring_params:
  monitor: val/loss
  mode: min
  verbose: true
  interval: epoch
