_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cotic.cotic.COTIC
  in_channels: 64
  kernel_size: 7
  nb_filters: 64
  nb_layers: 9
  num_types: ${num_types}
intensity_head:
  _target_: src.models.components.cotic.head.intensity_head.IntensityHead
  kernel_size: 7
  nb_filters: ${model.net.nb_filters}
  mlp_layers:
    - 32
#    - 32
#    - 16
  num_types: ${num_types}
downstream_head:
  _target_: src.models.components.cotic.head.downstream_head.DownstreamHead
  nb_filters: ${model.net.nb_filters}
  mlp_layers:
    - 32
#    - 32
#    - 16
  num_types: ${num_types}
uniform_sample_size: 5
optimizer:
  _target_: adan_pytorch.Adan
  _partial_: true
  lr: 1e-3
  betas:
    - 0.02
    - 0.08
    - 0.01
  weight_decay: 0.02
init_lr: ${model.optimizer.lr}
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.5
  patience: 10
  min_lr: 1e-6
warmup_steps: 1500
scheduler_monitoring_params:
  monitor: val/loss
  mode: min
  verbose: true
  interval: epoch
