_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cotic.cotic.COTIC
  in_channels: 256
  kernel_size: 3
  nb_filters: 128
  nb_layers: 11 # 7
  num_types: ${num_types}
  dropout: 0.3
  dilation_factor: 1.38
joined_head:
  _target_: src.models.components.cotic.head.joined_head.ProbabilisticJoinedHead # JoinedHead
  intensity_head:
    _target_: src.models.components.cotic.head.intensity_head.IntensityHeadLinear
    kernel_size: 1
    nb_filters: ${model.net.nb_filters}
    num_types: ${num_types}
  downstream_head:
    _target_: src.models.components.cotic.head.downstream_head.ProbabilisticDownstreamHead # DownstreamHeadSklearnLinear #DownstreamHeadLinear
    compute_every_n_epochs: 49
#    nb_filters: ${model.net.nb_filters} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
#    num_types: ${num_types} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
##    type_loss_coeff: 1 # DownstreamHeadLinear
##    time_loss_coeff: 10 # DownstreamHeadLinear
##    reductions: 2 # DownstreamHeadLinear
##      type: mean # DownstreamHeadLinear
##      time: mean # DownstreamHeadLinear
  uniform_sample_size: 50
optimizer:
  _target_: adan_pytorch.Adan
  _partial_: true
  lr: 0.07
  weight_decay: 0.008
init_lr: ${model.optimizer.lr}
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 1500
  eta_min: 1e-6
scheduler_monitoring_params:
  monitor: val/loss
  mode: min
  verbose: true
  interval: epoch
