_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.cotic.cotic.COTIC
  in_channels: 192
  kernel_size: 3
  nb_filters: 512
  nb_layers: 8 # 7
  num_types: ${num_types}
  dropout: 0.2
  dilation_factor: 1.29
joined_head:
  _target_: src.models.components.cotic.head.joined_head.ProbabilisticJoinedHead # JoinedHead
  intensity_head:
    _target_: src.models.components.cotic.head.intensity_head.IntensityHeadLinear
    kernel_size: 1
    nb_filters: ${model.net.nb_filters}
    num_types: ${num_types}
  downstream_head:
    _target_: src.models.components.cotic.head.downstream_head.ProbabilisticDownstreamHead # DownstreamHeadSklearnLinear #DownstreamHeadLinear
    compute_every_n_epochs: 99
#    nb_filters: ${model.net.nb_filters} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
#    num_types: ${num_types} # DownstreamHeadSklearnLinear, DownstreamHeadLinear
##    type_loss_coeff: 1 # DownstreamHeadLinear
##    time_loss_coeff: 10 # DownstreamHeadLinear
##    reductions: 2 # DownstreamHeadLinear
##      type: mean # DownstreamHeadLinear
##      time: mean # DownstreamHeadLinear
  uniform_sample_size: 50
optimizer:
  _target_: torch.optim.AdamW # adan_pytorch.Adan
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-6 #0.0033
init_lr: ${model.optimizer.lr}
scheduler: null
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
#  T_max: 260
#  eta_min: 1e-3
scheduler_monitoring_params:
  monitor: val/loss
  mode: min
  verbose: true
  interval: step
