_target_: src.models.rmtpp_model.RMTPPModule

num_class: 7
emb_dim: 10
hid_dim: 32
mlp_dim: 16
dropout: 0.1
alpha: 0.05
lr: 0.001

metrics:
  _target_: src.metrics.cont_cnn.CCNNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
  sim_size: 40
