_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.baselines.thp.Transformer
  num_types: 16
  d_model: 256
  d_rnn: 128
  d_inner: 1024
  n_layers: 4
  n_head: 4
  d_k: 64
  d_v: 64
  dropout: 0.1
  rnn: True
metrics:
  _target_: src.metrics.baselines.thp.THPMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.RocAuc
optimizer:
  name: adam
  params:
    lr: 1e-3
    weight_decay: 1e-5
