_target_: src.models.base_model.BaseEventModule

net:
  _target_: src.models.components.baselines.wavenet.WaveNet
  hyperparams: 
    nb_layers: 9
    kernel_size: 5
    nb_filters: 16
  in_channels: 32
  num_types: 8
metrics:
  _target_: src.metrics.baselines.wavenet.WNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.Accuracy
optimizer:
  name: adam
  params:
    lr: 1e-3
    weight_decay: 1e-5
