_target_: src.models.extra_head_model.ExtrHeadEventModule

net:
  _target_: src.models.components.baselines.wavenet_intens.WaveNetIntens
  hyperparams: 
    nb_layers: 9
    kernel_size: 5
    nb_filters: 16
    hidden_size: 32
  in_channels: 32
  num_types: 5
  interpolator:
    _target_: src.models.components.baselines.wavenet_intens.IntensPredictor
    in_channels: 32
    hidden1: 64
    hidden2: 128
    hidden3: 64
    num_types: 5
head:
  __target__: src.models.components.baselines.wavenet_intens.PredictionHead
  in_channels: 32
  num_types: 5
metrics:
  _target_: src.metrics.baselines.wavenet.WNMetrics
  return_time_metric:
    _target_: src.utils.metrics.MAE
  event_type_metric:
    _target_: src.utils.metrics.RocAuc
optimizer:
  name: adam
  params:
    lr: 1e-3
    weight_decay: 1e-5
