# https://www.comet.ml

comet:
 _target_: pytorch_lightning.loggers.comet.CometLogger
 api_key: ${oc.env:COMET_API_TOKEN}
 project_name: ???
 workspace: ${oc.env:COMET_WORKSPACE}
 experiment_name: ${name}
