# https://www.comet.ml

comet:
 _target_: pytorch_lightning.loggers.comet.CometLogger
 api_key: ${oc.env:COMET_API_TOKEN}
 project_name: amznew
 workspace: ${oc.env:COMET_WORKSPACE_NAME}
 experiment_name: ${name}
